import { existsSync, readFileSync } from 'node:fs';

import assert from 'node:assert/strict';
import { describe, it } from 'node:test';

import { tryParseLooseJsObject } from './parse-js-object.ts';
import { combineMarkerFileResults, parseUnminedMarkersSource } from './parse-markers-source.ts';

const PROPERTIES_FROM_REAL_EXPORT = `/* Autogenerated file, overwritten by uNmINeD on map generation. */
var UnminedMapProperties = {
    minZoom: -6,
    maxZoom: 0,
    defaultZoom: 0,
    imageFormat: "jpeg",
    markers: new Array(),
    centerX: 0,
    centerZ: 0
}
`;

const CUSTOM_MARKERS_WITH_COMMENT_BRACES = `/*
Example:
{
    x: 7,
    z: -36,
    text: "Example",
}
uNmINeD does not overwrite this file.
*/

UnminedCustomMarkers = {
  isEnabled: true,
  markers: [
    {
      x: 155,
      z: -50,
      image: "custom.pin.png",
      text: "Casa",
      textColor: "#f8fafc",
    },
  ],
};
`;

const DISABLED_CUSTOM_MARKERS = `UnminedCustomMarkers = {
    isEnabled: false,
    markers: [
      { x: 1, z: 2, text: "Template" },
    ],
};
`;

describe('tryParseLooseJsObject', () => {
  it('reads minZoom and jpeg from a real unmined.map.properties.js', () => {
    const parsed = tryParseLooseJsObject(PROPERTIES_FROM_REAL_EXPORT);
    assert.ok(parsed && typeof parsed === 'object');
    const props = parsed as Record<string, unknown>;
    assert.equal(props.minZoom, -6);
    assert.equal(props.maxZoom, 0);
    assert.equal(props.imageFormat, 'jpeg');
    assert.equal(props.centerX, 0);
    assert.equal(props.centerZ, 0);
  });
});

describe('parseUnminedMarkersSource', () => {
  it('imports Casa from custom.markers.js even when the header comment contains braces', () => {
    const result = parseUnminedMarkersSource(CUSTOM_MARKERS_WITH_COMMENT_BRACES);
    assert.equal(result.status, 'ok');
    if (result.status !== 'ok') {
      return;
    }
    assert.equal(result.markers.length, 1);
    assert.equal(result.markers[0]?.nome, 'Casa');
    assert.equal(result.markers[0]?.x, 155);
    assert.equal(result.markers[0]?.z, -50);
    assert.equal(result.markers[0]?.dimensao, 'overworld');
    assert.equal(result.markers[0]?.icon, 'custom.pin.png');
    assert.equal(result.markers[0]?.color, '#f8fafc');
  });

  it('does not import pins when isEnabled is false', () => {
    const result = parseUnminedMarkersSource(DISABLED_CUSTOM_MARKERS);
    assert.equal(result.status, 'ok');
    if (result.status !== 'ok') {
      return;
    }
    assert.deepEqual(result.markers, []);
  });

  it('keeps UnminedCustomMarkers pins in Overworld even if a stray dimension field exists', () => {
    const result = parseUnminedMarkersSource(`UnminedCustomMarkers = {
      isEnabled: true,
      markers: [{ x: 1, z: 2, text: "Casa", dimensao: "nether" }],
    };`);
    assert.equal(result.status, 'ok');
    if (result.status !== 'ok') {
      return;
    }
    assert.equal(result.markers[0]?.dimensao, 'overworld');
  });
});

describe('combineMarkerFileResults', () => {
  it('reports missing when there are no marker files', () => {
    const result = combineMarkerFileResults([]);
    assert.equal(result.status, 'missing');
  });

  it('keeps the step failed when one file fails even if another is a disabled template', () => {
    const result = combineMarkerFileResults([
      { status: 'failed', error: 'Não foi possível interpretar broken.json' },
      { status: 'ok', markers: [] },
    ]);
    assert.equal(result.status, 'failed');
  });

  it('merges pins from files that parsed', () => {
    const result = combineMarkerFileResults([
      {
        status: 'ok',
        markers: [{ nome: 'Casa', dimensao: 'overworld', x: 155, z: -50 }],
      },
      { status: 'ok', markers: [] },
    ]);
    assert.equal(result.status, 'ok');
    if (result.status !== 'ok') {
      return;
    }
    assert.equal(result.markers[0]?.nome, 'Casa');
  });
});

const REAL_EXPORT_ROOT = 'D:/projetos/personal/minecraft/output';

describe('real uNmINeD CLI export', () => {
  const markersPath = `${REAL_EXPORT_ROOT}/custom.markers.js`;
  const propertiesPath = `${REAL_EXPORT_ROOT}/unmined.map.properties.js`;
  const netherMarkersPath = `${REAL_EXPORT_ROOT}/nether/custom.markers.js`;

  it('imports named pins such as Casa from the on-disk custom.markers.js', { skip: !existsSync(markersPath) }, () => {
    const result = parseUnminedMarkersSource(readFileSync(markersPath, 'utf8'));
    assert.equal(result.status, 'ok');
    if (result.status !== 'ok') {
      return;
    }
    const casa = result.markers.find((marker) => marker.nome === 'Casa');
    assert.ok(casa);
    assert.equal(casa?.x, 155);
    assert.equal(casa?.z, -50);
  });

  it('does not import pins from a disabled nether custom.markers.js', { skip: !existsSync(netherMarkersPath) }, () => {
    const result = parseUnminedMarkersSource(readFileSync(netherMarkersPath, 'utf8'));
    assert.equal(result.status, 'ok');
    if (result.status !== 'ok') {
      return;
    }
    assert.deepEqual(result.markers, []);
  });

  it('reads jpeg and negative minZoom from unmined.map.properties.js', { skip: !existsSync(propertiesPath) }, () => {
    const parsed = tryParseLooseJsObject(readFileSync(propertiesPath, 'utf8'));
    assert.ok(parsed && typeof parsed === 'object');
    const props = parsed as Record<string, unknown>;
    assert.equal(props.imageFormat, 'jpeg');
    assert.equal(props.minZoom, -6);
  });
});
